hosts:
  - composer.local

plugins:
   - query-monitor

themes:
   - twentyfifteen

extensions:
   - Tester

disabled_extensions:
   - chassis/mailhog

synced_folders:
  .: /vagrant/content/plugins/this-plugin
